<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Jurnal Transaksi</title>
    <style type="text/css">
        body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 11pt;
            margin: 20px;
            color: #333;
        }

        /* 
        table.header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        } */

        table.header-table td {
            border: none;
            padding: 3px 0;
        }

        h1 {
            font-size: 16pt;
            margin: 0;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .info-table td {
            border: none;
            padding: 2px 0;
            font-size: 11pt;
        }

        .table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }

        .table th,
        .table td {
            border: 1px solid #333;
            padding: 5px;
            text-align: center;
        }

        .table th {
            background-color: #e0e0e0;
        }

        .table td.left {
            text-align: left;
        }

        .total-row {
            font-weight: bold;
            background-color: #f0f0f0;
        }

        .footer {
            text-align: center;
            font-size: 10pt;
            margin-top: 30px;
            color: #666;
        }
    </style>
</head>

<body>
    <table>
        <tr>
            <td style="text-align:center;" colspan="2">
                <h1>Jurnal Transaksi</h1>
            </td>
        </tr>
        <tr>
            <td style="width:15%; text-align: left;">
                <strong>Tanggal</strong>
            </td>
            <td>
                <?php echo ": " . $jurnal->tanggal; ?>
            </td>
        </tr>
        <tr>
            <td style="width:15%; text-align: left;">
                <strong>Referensi</strong>
            </td>
            <td>
                <?php echo ": " . $jurnal->referensi; ?>
            </td>
        </tr>
        <tr>
            <td style="width:15%; text-align: left;">
                <strong>Deskripsi</strong>
            </td>
            <td>
                <?php echo ": " . $jurnal->deskripsi; ?>
            </td>
        </tr>
    </table>
    <br>
    <br>
    <table class="table">
        <tr>
            <td style="width:5%;"><b>No.</b></td>
            <td style="width:35%;"><b>Akun</b></td>
            <td style="width:30%;"><b>Debit</b></td>
            <td style="width:30%;"><b>Kredit</b></td>
        </tr>
        <?php
        $no = 1;
        $totalDebit = 0;
        $totalKredit = 0;
        foreach ($jurnal->detail as $detail):
            $totalDebit += $detail->debit;
            $totalKredit += $detail->kredit;
            ?>
            <tr>
                <td>
                    <?php echo $no++; ?>
                </td>
                <td class="left">
                    <?php echo $detail->nama_akun . ' (' . $detail->kode_akun . ')'; ?>
                </td>
                <td style="text-align: right;">
                    <?php echo number_format($detail->debit, 2, ',', '.'); ?>
                </td>
                <td style="text-align: right;">
                    <?php echo number_format($detail->kredit, 2, ',', '.'); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <tfoot>
            <tr class="total-row">
                <td colspan="2">Total</td>
                <td style="text-align: right;">
                    <?php echo number_format($totalDebit, 2, ',', '.'); ?>
                </td>
                <td style="text-align: right;">
                    <?php echo number_format($totalKredit, 2, ',', '.'); ?>
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="footer">
        <p>Generated by Sistem Akuntansi &mdash;
            <?php echo date('Y'); ?>
        </p>
    </div>
</body>

</html>