<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Laporan Akuntansi</title>
    <style type="text/css">
        body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 11pt;
            margin: 20px;
            color: #333;
        }

        /* Header disusun menggunakan tabel tanpa border */
        table.header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.header-table td {
            border: none;
            padding: 3px 0;
        }

        h1 {
            font-size: 16pt;
            text-align: center;
            margin-bottom: 0;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .info-table td {
            border: none;
            padding: 2px 0;
            font-size: 11pt;
        }

        /* Tabel laporan */
        table.laporan-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table.laporan-table th,
        table.laporan-table td {
            border: 1px solid #333;
            padding: 5px;
            text-align: center;
        }

        table.laporan-table th {
            background-color: #e0e0e0;
        }

        table.laporan-table td.left {
            text-align: left;
        }

        table.laporan-table tfoot td {
            font-weight: bold;
            background-color: #f0f0f0;
        }

        .footer {
            text-align: center;
            font-size: 10pt;
            margin-top: 20px;
            color: #666;
        }
    </style>
</head>

<body>
    <!-- Header menggunakan tabel tanpa border -->
    <table class="header-table">
        <tr>
            <td style="text-align:center;">
                <h1>Laporan Akuntansi (Trial Balance)</h1>
            </td>
        </tr>
    </table>
    <table class="laporan-table">
        <thead>
            <tr>
                <th style="width:80px;">Kode Akun</th>
                <th>Nama Akun</th>
                <th style="width:100px;">Total Debit</th>
                <th style="width:100px;">Total Kredit</th>
                <th style="width:100px;">Saldo</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $totalDebit = 0;
            $totalKredit = 0;
            $totalSaldo = 0;
            foreach ($laporan as $row):
                $totalDebit += $row->total_debit;
                $totalKredit += $row->total_kredit;
                $totalSaldo += $row->saldo;
                ?>
                <tr>
                    <td>
                        <?php echo $row->kode_akun; ?>
                    </td>
                    <td class="left">
                        <?php echo $row->nama_akun; ?>
                    </td>
                    <td style="text-align:right;">
                        <?php echo number_format($row->total_debit, 2, ',', '.'); ?>
                    </td>
                    <td style="text-align:right;">
                        <?php echo number_format($row->total_kredit, 2, ',', '.'); ?>
                    </td>
                    <td style="text-align:right;">
                        <?php echo number_format($row->saldo, 2, ',', '.'); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2" style="text-align:right;">Total</td>
                <td style="text-align:right;">
                    <?php echo number_format($totalDebit, 2, ',', '.'); ?>
                </td>
                <td style="text-align:right;">
                    <?php echo number_format($totalKredit, 2, ',', '.'); ?>
                </td>
                <td style="text-align:right;">
                    <?php echo number_format($totalSaldo, 2, ',', '.'); ?>
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="footer">
        <p>Generated by Sistem Akuntansi &mdash;
            <?php echo date('Y'); ?>
        </p>
    </div>
</body>

</html>